language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-network-checks.gemspec
- gem install sensu-plugins-network-checks-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: l79xZquLcaZ1AqR58Vahu2PhIwz4UHpVN3vJZYOOO2phYC5qi1Q4UAQsg1Yw3sgY/3wrjtTPGo26MbGDs86oZXE9Gq8L9paIyRDGhTWp/Y5+q7vUx7gBGu/r1kVco2UTwXAUr/cWA+WbiqYYlTiTIxBLJlsbE2mPGOnW2H97cCc=
  gem: sensu-plugins-network-checks
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-network-checks
